config/routes.rb
Ownbox::Application.routes.draw do
  root 'home#index'

  get '/login', to: 'session#new', as: :login
  post '/login', to: 'session#create', as: :login_post
  get '/logout', to: 'session#destroy', as: :logout

  get '/register', to: 'registration#new', as: :register_user
  post '/register', to: 'registration#create', as: :create_user
  get '/register/success', to: 'registration#success', as: :register_user_success
  get '/register/activate', to: 'registration#activate', as: :activate_user
  post '/register/check_invite', to: 'registration#check_invite', as: :check_invite

  get '/get/:user_name(/*path)', to: 'file#get', as: :get_item, :format => false
  get '/preview/:user_name(/*path)', to: 'file#preview', as: :preview_item, :format => false

  get '/home(/*path)', to: 'directory#index', defaults: { user_name: :current_user }, as: :current_user_items_index, :format => false
  get '/shares/(:user_name(/*path))', to: 'directory#index', as: :shares_index, :format => false

  post '/directory/create', to: 'directory#create'
  get '/directory/deleteModal', to: 'directory#delete_modal'
  post '/directory/destroy', to: 'directory#destroy'

  post '/export', to: 'export#begin'
  get '/export/status', to: 'export#status'
  get '/export/result', to: 'export#result'
  get '/export/delete', to: 'export#delete'

  post '/file/upload', to: 'file#upload'

  get '/users', to: 'users#index', as: :users_index
  get '/users/:name', to: 'users#show', as: :show_user

  namespace :settings do
    get '/profile', to: 'profile#edit', as: :edit_profile
    patch '/profile', to: 'profile#update', as: :update_profile

    get '/shares', to: 'shares#index', as: :shares_index
    post '/shares', to: 'shares#create', as: :create_share
    patch '/shares', to: 'shares#update', as: :update_share
    delete '/shares', to: 'shares#delete', as: :delete_share

    get '/shares/:share_id/permissions/', to: 'share_permissions#index', as: :share_permissions_index
    patch '/shares/:share_id/permissions/', to: 'share_permissions#update', as: :update_share_permissions

    get '/security', to: 'security#edit', as: :edit_security
    patch '/security', to: 'security#update', as: :update_security
  end

  namespace :admin do
    get '/', to: 'home#index', as: :home

    get '/users', to: 'users#index', as: :users_index
    post '/users', to: 'users#create', as: :create_user
    post '/users/:user_name/send_email', to: 'users#send_activation_email', as: :send_user_activation_email
    patch '/users/:user_name', to: 'users#update', as: :update_user

    get '/invites', to: 'invites#index', as: :invites_index
    post '/invites', to: 'invites#create', as: :create_invite
    delete '/invites/:code', to: 'invites#delete', as: :delete_invite
  end

end

app/models/session.rb
class Session < ActiveRecord::Base
  self.table_name = 'security.sessions'

  belongs_to :user
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  
  def new
    if (authenticated?)
        redirect_to root_path
        return
    end
    @login = Login.new;
  end

  def create
    login = params[:login]
    user = User.find_by_email(login[:email])
    if (user)
        if (user.locked)
            flash.now.alert = t('errors.messages.user_locked')
        elsif (!user.approved)
            flash.now.alert = t('errors.messages.account_not_activated')
        elsif (!user.authenticate(login[:password]))
            flash.now.alert = t('errors.messages.invalid_email_or_password')
        else
          login_user user, login[:remember]
          redirect_to root_path
          return
        end
    else 
        flash.now.alert = t('errors.messages.invalid_email_or_password')
    end
    @login = Login.new(email: login[:email], remember: login[:remember])
    render 'new'
  end

  def destroy
    logout_user
    redirect_to login_path
  end

end

app/helpers/session_helper.rb
module SessionHelper

  def current_session
    session_id = cookies['session']
    return nil if !session_id

    session = Session.find_by_id(session_id)
    return nil if !session || session.closed || DateTime.now > session.expires_at;
    session
  end

  def current_user
    session = current_session;
    return nil if !session 
    session.user
  end

  def authenticated?
    return false if !current_user
    true
  end

  def login_user(user, persistence)
    session = Session.new
    session.id = SecureRandom.uuid
    session.user = user;
    session.persistent = persistence
    lifetime = persistence ? Settings.security.persistent_session_lifetime : Settings.security.session_lifetime
    session.expires_at = DateTime.now + lifetime
    session.save!

    cookies['session'] = {   
        value: session.id,
        expires: session.expires_at,
        httponly: true
    }
  end

  def logout_user
    return if !current_session

    session = Session.find(current_session.id)
    session.closed = true
    session.closed_at = DateTime.now
    session.save!

    cookies.delete 'session'
  end 

end

app/views/session/new.html.erb
<div class="container">
    <div class="row">
        <div class="form-box col-sm-6 col-md-4 col-md-offset-4">
            <h1 class="text-center login-title"><%= t ".login_to_continue" %></h1>
            <div class="account-wall">
                <img class="profile-img" src="https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=120" alt="">
                <%= form_for @login, url: login_post_path, html: { class: "form-signin" } do |f| %>
                    <%= f.email_field :email, class: "form-control", placeholder: t(".email") %>
                    <%= f.password_field :password, class: "form-control", placeholder: t(".password") %>
                    <label class="checkbox" for="login_remember">
                        <%= f.check_box :remember %>
                        <%= t '.remember' %>
                    </label>
                    <%= f.submit t(".login"), class: "btn btn-lg btn-primary btn-block" %>
                    <br/>
                    <% if Settings.security.registration_mode != :disabled %>
                    <a href="<%= register_user_path %>" class="">
                        <%= t ".create_new_account" %>
                    </a>
                    <% end %>
                    <a href="#" class="pull-right">
                        <%= t ".need_help" %>
                    </a>
                <% end %>
            </div>
        </div>
    </div>
</div>