config/routes.rb
Ownbox::Application.routes.draw do
  root 'home#index'

  get '/login', to: 'session#new', as: :login
  post '/login', to: 'session#create', as: :login_post
  get '/logout', to: 'session#destroy', as: :logout

  get '/register', to: 'registration#new', as: :register_user
  post '/register', to: 'registration#create', as: :create_user
  get '/register/success', to: 'registration#success', as: :register_user_success
  get '/register/activate', to: 'registration#activate', as: :activate_user
  post '/register/check_invite', to: 'registration#check_invite', as: :check_invite

  get '/get/:user_name(/*path)', to: 'file#get', as: :get_item, :format => false
  get '/preview/:user_name(/*path)', to: 'file#preview', as: :preview_item, :format => false

  get '/home(/*path)', to: 'directory#index', defaults: { user_name: :current_user }, as: :current_user_items_index, :format => false
  get '/shares/(:user_name(/*path))', to: 'directory#index', as: :shares_index, :format => false

  post '/directory/create', to: 'directory#create'
  get '/directory/deleteModal', to: 'directory#delete_modal'
  post '/directory/destroy', to: 'directory#destroy'

  post '/export', to: 'export#begin'
  get '/export/status', to: 'export#status'
  get '/export/result', to: 'export#result'
  get '/export/delete', to: 'export#delete'

  post '/file/upload', to: 'file#upload'

  get '/users', to: 'users#index', as: :users_index
  get '/users/:name', to: 'users#show', as: :show_user

  namespace :settings do
    get '/profile', to: 'profile#edit', as: :edit_profile
    patch '/profile', to: 'profile#update', as: :update_profile

    get '/shares', to: 'shares#index', as: :shares_index
    post '/shares', to: 'shares#create', as: :create_share
    patch '/shares', to: 'shares#update', as: :update_share
    delete '/shares', to: 'shares#delete', as: :delete_share

    get '/shares/:share_id/permissions/', to: 'share_permissions#index', as: :share_permissions_index
    patch '/shares/:share_id/permissions/', to: 'share_permissions#update', as: :update_share_permissions

    get '/security', to: 'security#edit', as: :edit_security
    patch '/security', to: 'security#update', as: :update_security
  end

  namespace :admin do
    get '/', to: 'home#index', as: :home

    get '/users', to: 'users#index', as: :users_index
    post '/users', to: 'users#create', as: :create_user
    post '/users/:user_name/send_email', to: 'users#send_activation_email', as: :send_user_activation_email
    patch '/users/:user_name', to: 'users#update', as: :update_user

    get '/invites', to: 'invites#index', as: :invites_index
    post '/invites', to: 'invites#create', as: :create_invite
    delete '/invites/:code', to: 'invites#delete', as: :delete_invite
  end

end

app/views/layouts/_error_modal.html.erb
<%= bt_modal id: "unhandled-error", header: t('.modal_header') do |m| %>
  <% m.body do %>
    <p><%= t('.modal_message') %></p>
    <p><%= t('.error_details') %></p>
    <pre class="details"></pre>
  <% end %>
  <% m.footer do %>
    <%= bt_button text: t("commands.ok"), data: { dismiss: "modal" } %>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="site-footer text-muted">
    <%= Settings.app_name %> v0.1
</footer>

app/views/layouts/_loader.html.erb
<div class="site-loader">
  <div class="p1"></div>
  <div class="p2"></div>
  <div class="p3"></div>
  <div class="p4"></div>
  <div class="p5"></div> 
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-ownbox navbar-default navbar-static-top navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">
                <img src="<%= image_path "ownbox.png" %>" />
                <span><%= Settings.app_name %></span>
            </a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse-1">
            <ul class="nav navbar-nav">
                <% if authenticated? %>
                    <li>
                        <%= bt_button id: "private-data", text: t(".private_data"), 
                                      href: current_user_items_index_path, style: :link %>
                    </li>
                    <li>
                        <%= bt_button id: "shared-data", text: t(".shared_data"),
                                      href: shares_index_path, style: :link %>
                    </li>
                <% end %>       
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <% if authenticated? %>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <%= current_user.display_name %> <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li role="presentation" class="dropdown-header"><%= current_user.display_name %></li>
                            <li role="presentation" class="dropdown-header"><%= current_user.email %></li>

                            <li role="button">
                                <%= link_with_icon t(".settings"), "gears", settings_edit_profile_path %>
                            </li>
                            <li role="button">
                                <%= link_with_icon t(".logout"), "sign-out", logout_path %>
                            </li>
                            
                            <% if current_user.is_admin? %>
                                <li role="presentation" class="divider"></li>
                                <li role="presentation" class="dropdown-header">
                                    <%= t '.admin_area' %>
                                </li>
                                <li role="button">
                                    <%= bt_button text: t(".administration"), icon: "gears", 
                                                  href: admin_home_path, style: :link %>
                                <li>
                            <% end %>
                        </ul>
                    </li>
                <% else %>
                    <li role="button">
                        <%= bt_button text: t("commands.login"), icon: "sign-in", href: login_path, style: :link %>
                    </li>
                <% end %>
            </ul>
        </div>
        
</div>
</div>

app/views/layouts/admin.html.haml
- content_for :sub_nav do
  .navbar.navbar-default.navbar-second.navbar-static-top
    .container
      %ul.nav.navbar-nav.navbar-nav-justified
        %li=link_with_icon t('.settings'), "sliders", admin_users_index_path
        %li=link_with_icon t('.users'), "users", admin_users_index_path
        %li=link_with_icon t('.ivites'), "ticket", admin_invites_index_path
-content_for :content do
  .row
    .col-md-3
      = content_for?(:filters) ? yield(:filters) : ''
    .col-md-9
      -content_for :messages do '' end
      =render 'layouts/messages'
      =yield
-@hide_messages = true
=render template: "layouts/application"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <title><%= Settings.app_name %></title>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="icon" type="image/png" href="<%= image_path "ownbox_xs.png" %>" />
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= stylesheet_link_tag params[:controller], media: "all" %>
    <%= yield :styles %>
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <%= render 'layouts/loader' %>
    <div class="site-content">
        <%= render 'layouts/navbar' %>
        <%= content_for?(:sub_nav) ? yield(:sub_nav) : '' %>
        <div class="container main-container">
            <%= render('layouts/messages') if !@hide_messages %>
            <%= content_for?(:content) ? yield(:content) : yield %>
        </div>
    </div>
    <%= render 'layouts/footer' %>
    <%= render 'layouts/error_modal' %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag params[:controller] %>
    <%= yield :scripts %>
</body>
</html>

app/views/layouts/settings.html.haml
- content_for :sub_nav do
  .navbar.navbar-default.navbar-second.navbar-static-top
    .container
      %ul.nav.navbar-nav.navbar-nav-justified
        %li=link_with_icon t('.profile'), "user", settings_edit_profile_path
        %li=link_with_icon t('.shares'), "folder", settings_shares_index_path
        %li=link_with_icon t('.security'), "shield", settings_edit_security_path
- content_for :content do
  - content_for :messages do '' end
  = render 'layouts/messages'
  = yield
- @hide_messages = true
= render template: "layouts/application"